name : Building
on: [push]
jobs: 
  building:
    runs-on: ubuntu-laster
    steps:
      - use: actions/checkout#v3
      - use: actions/setup-python@v4
        with:
          python-version: '3.10'