name : Building
on: [push]
jobs: 
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry build
      - run: ls ${{ github.workspace }}

      - name: Publish to GH Release        
        uses: softprops/action-hg-release@v1
        with:
          files: ${{ github.workspace }}/dist/*