name : Building
on: [push]
jobs: 
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry build
      - run: ls ${{ github.workspace }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 0.1.0
          release_name: Release 0.1.
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false