name : Building
on: [push]
jobs: 
  building:
    runs-on: ubuntu-laster
    steps:
      - uses: actions/checkout#v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'